server:
  port: ${port:9092}
eureka:
  instance:
    hostname: localhost
    #when the application registers with eureka, it uses its IP address rather than its hostname
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9093/eureka/  
